# item process values
CLIENT_ONBOARDING_SURVEY = "Client Onboarding Survey"
PAYMENT_ERROR_EMAIL = "Payment error email"
RUNNING_FLOW = "Running flow"
ANNUAL_REPORT_UPLOADED = "Annual Report Uploaded"
CALCULATE_NPS_RUNNING = "Calculate NPS Running"
CALCULATE_NPS_ONBOARDING = "Calculate NPS Onboarding"
KICKOFF_QUESTIONNAIRE_COMPLETED = "Kickoff Questionnaire Completed"
KICKOFF_CALL_SCHEDULED = "Kickoff Call Scheduled"
KICKOFF_CALL_CANCELLED = "Kickoff Call Cancelled"
TRANSITION_PLAN_SUBMITTED = "Transition Plan Submitted"
BK_TRAINING_CALL_SCHEDULED = "BK Training Call Scheduled"
BK_TRAINING_CALL_CANCELLED = "BK Training Call Cancelled"
BANK_CONNECT = "Bank connect"
